version: '3.9'

services:
  # ───── PostgreSQL ───────────────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 787898
      POSTGRES_DB: idcc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./idcc/docker/seed.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [idcc-net]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  # ───── Redis ────────────────────────────────────────────────────────────────
  cache:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
    networks: [idcc-net]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  # ───── API ──────────────────────────────────────────────────────────────────
  idcc:
    image: idcc
    build:
      context: .
      dockerfile: idcc/Dockerfile
    depends_on:
      cache:      { condition: service_started }
    ports: ["5000:5000"]
    networks: [idcc-net]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db_data:

networks:
  idcc-net:
    driver: bridge
